spring:
  liquibase:
    change-log: db.changelog/liquibase-changelog.xml
  datasource:
    url: jdbc:h2:mem:weatherdb:~/liquibase;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2
      enabled: true

ipgeolocation:
  key: 2d62c9bc49894f548c0a134d131b4456

weatherapi:
  basePath: http://api.weatherapi.com/v1/current.json
  apiKey: 2ddeb315e19746a5ab600644222211